SET NAMES UTF8;
DROP DATABASE IF EXISTS haochedai;
CREATE DATABASE haochedai CHARSET=utf8;
USE haochedai;
CREATE TABLE  users(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(8),
	upwd VARCHAR(16),
	email  VARCHAR(20),
	phone VARCHAR(11)
);
INSERT INTO users VALUES(NULL,"TOM","123456","164953@qq.COM","13757745874");